### ISSUE TITLE
[feat] 검색 페이지 UI 마크업 및 기능 구현

### ISSUE THREAD

**Issue by whoisrey** [FRONTENDSCHOOL5/final-17-breath-connect#43]
## 💡 작업할 내용 
- [x] 검색 페이지 UI 마크업 및 기능 구현
- [x] 기능 구현 (추후)
- 10개 이후 데이터 (...더보기)`버튼` 활성화
- `setTimeOut()` 함수 활용

## 📝 구현 방법 및 예상 동작

<img width="130" alt="search-2 (계정검색)" src="https://github.com/FRONTENDSCHOOL5/final-17-breath-connect/assets/106927728/77ffc3c2-f1f3-4a01-8938-ac078fe29994">
➡️
<img width="130" alt="search-2 (계정검색)" src="https://github.com/FRONTENDSCHOOL5/final-17-breath-connect/assets/106927728/9459d24a-6372-4d51-9f12-f8a34fb2f870">

## ✏️ 참고사항
-

**Comment by sy-paik** [comment]
오아.. 화이탱입니다 양래님!! 👍👍👍

**Comment by whoisrey** [comment]
완료!
